id = "sonokai"
name = "Sonokai"
version = "0.0.2"
schema_version = 1
authors = ["ciathefed <ciathefed@protonmail.com>"]
repository = "https://github.com/ciathefed/sonokai-zed"
description = "Sonokai Color Scheme for Zed"
